#+TITLE:   lang/durand-org
#+DATE:    novembre 28, 2019
#+STARTUP: inlineimages

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
- [[#configuration][Configuration]]
- [[#troubleshooting][Troubleshooting]]

* Description
My org configurations.

+ I have three specific files for =org-agenda=: notes.org, aujourdhui.org, and agenda.org.
  Other files may be added later, but at the moment I only use those three files for
  agenda.
+ My agenda is customized by having *pages*. Each page corresponds to a section in
  =org-super-agenda=. And there are key-bindings to navigate these pages conveniently.
  here the strange key-binding is because I use a French keyboard layout, and these keys
  are neighbours and easy to reach, for me.

  |-----+----------------|
  | key | action         |
  |-----+----------------|
  | )   | next page      |
  | -   | previous page  |
  | S-) | next group     |
  | S-- | previous group |
  | DEL | first page     |
  | à   | last page      |
  |-----+----------------|

+ I hate to edit in a pop up window, since I have a rather small screen. So I add an
  advice to =org-edit-special= so that it deletes other windows after it pops up the buffer.

+ I have a specific major mode for inserting Greek. Usually I insert Greek in a source
  block in =org-mode=, so there is a custom =org-tempo= snippet for this:
  #+BEGIN_EXAMPLE
  <g should expand to durand-greek mode source block.
  #+END_EXAMPLE

  Unfortunately currently this is not working, perhaps because some settings are wrongly
  configured. I shall investigate the cause later when I have enough time.

+ Include links to packages & external things where possible

** Module Flags
This module provides no flags.

** Plugins
+ [[https://github.com/alphapapa/org-super-agenda][org-super-agenda]]

* Prerequisites
This module has no prerequisites.

* TODO Features
An in-depth list of features, how to use them, and their dependencies.

* TODO Configuration
How to configure this module, including common problems and how to address them.

* TODO Troubleshooting
Common issues and their solution, or places to look for help.
